apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: custom-pod-delete 
  version: 0.1.0
  annotations:
    categories: sample-category
spec:
  displayName: custom-pod-delete 
  categoryDescription: >
    Deletes a pod belonging to a deployment/statefulset/daemonset 
  keywords: 
    - "pods" 
    - "kubernetes" 
    - "sample-category" 
    - "exec"
  platforms: 
    - "Minikube"
  maturity: alpha
  maintainers: 
    - name: ispeakc0de 
      email: shubham@chaosnative.com 
  minKubeVersion: 1.12.0 
  provider: 
    name: ChaosNative
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: latest
  links: 
    - name: Documentation 
      url: https://docs.litmuschaos.io/docs/getstarted/ 
  icon:
    - url: 
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/sample-category/custom-pod-delete/experiment.yaml