apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: sample-category 
  version: 0.1.0
  annotations:
    categories: sample-category
spec:
  displayName: sample-category chaos
  categoryDescription: >
    Deletes a pod belonging to a deployment/statefulset/daemonset 
  experiments:
  - custom-pod-delete
  keywords: 
    - "pods" 
    - "kubernetes" 
    - "sample-category" 
    - "exec"
  maintainers: 
    - name: ispeakc0de 
      email: shubham@chaosnative.com
  minKubeVersion: 1.12.0 
  provider: 
    name: ChaosNative
  links: 
    - name: Documentation 
      url: https://docs.litmuschaos.io/docs/getstarted/ 
  icon:
    - url: 
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/sample-category/experiments.yaml